### ISSUE TITLE
autocannon should support standard definitions of http headers

### ISSUE THREAD

**Issue by phra** [mcollina/autocannon#133]
hi,

i was using `autocannon` to stress test my web application and i find out that `autocannon` requires passing custom HTTP headers using a non standard format, specifically `-H "Content-Type=application/json"`, that is not conformant to HTTP specs and cURL usage. if you try to launch `autocannon` with the standard syntax `-H "Content-Type: application/json" it will produce malformed HTTP headers, as in the following screenshot:

![image](https://user-images.githubusercontent.com/984628/39999243-e594b8ee-5788-11e8-9994-cffac478975a.png)

i will send a PR extending the existing logic to manage the standard syntax and avoid a breaking change in the usage.

**Comment by gleb-s** [comment]
With fix applied I have an issue now, when my content-type is complex and looks like this: `content-type: application/json;odata=verbose`.
So, according to the logics from [this commit](https://github.com/phra/autocannon/commit/532349fb2318becacf73041604f6dea91394b36d#diff-b8cd744f56f8425866b8960637fe3f3bR96), I suppose, that my server is getting header like this:
`content-type: application/json;odata: verbose`. 
So it would be nice, if someone could fix it.

Also, I would like to see property for proxy configuration, because it's very hard to troubleshoot requests, when using this from cmd line.
