### ISSUE TITLE
Session recording / HAR support

### ISSUE THREAD

**Issue by mcollina** [mcollina/autocannon#185]
As titled!

**Comment by krainboltgreene** [comment]
Is it maybe worth doing this as a tool that wraps around autocannon?

**Comment by mcollina** [comment]
that’s also ok! I’d be happy to add a link!

**Comment by feugy** [comment]
Just a clarification (after a chat with Matteo): this issue is about taking HAR files as in input: their entries will be replayed.
It is not about exporting a benchmark results in an HAR file.

Given there could be hundreds of requests (and more) in results, visualizing them makes little sense.
That said, Pull Requests are welcome if someone absolutely needs it.

**Comment by krainboltgreene** [comment]
Hell yeah open source!

(disclaimer: I do not remember this issue at all nor this tool)
