### ISSUE TITLE
API Testing E2E

### ISSUE THREAD

**Issue by KayHS** [mcollina/autocannon#190]
How do i pass a variable from one request to another request. I need to load test a chain of api endpoints that rely on a previous request response for its params.

**Comment by mcollina** [comment]
You can use https://github.com/mcollina/autocannon/blob/master/samples/modifying-request.js.

**Comment by KKHAN1991** [comment]
@mcollina do i create a new auto cannon instance for each request?

**Comment by mcollina** [comment]
no. you just call set* methods between requests.

**Comment by KKHAN1991** [comment]
@mcollina 

Sorry i don't quite understand what you are suggesting to me do.

Please let me show you some code of what im trying to achieve, because i had it is something simple i can be shown once and then i would know how to do it for further requests i need to make/modify.

```
autocannon({
    url: "http://0.0.0.0:3002",
    connections: 100,
    duration: 10,
    requests: [{
        method: 'POST', // this should be a put for modifying secret details
        path: '/api/v2/auth',
        headers: { 
            'Content-type': 'application/json; charset=utf-8'
        },
        body: JSON.stringify({
            "productId": "sefsefsefsefsef",
        })
    },
    {
        method: 'POST', // this should be a put for modifying secret details
        path: '/api/v2/sessions',
        headers: { 
            'Authorization': "Bearer " + "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGNoZWNrIjp7InByb2R1Y3RJZCI6IjU2NzI5YjZiNzdjODIyODhmNzQ2YzBjZiIsImRvY3VtZW50Ijp0cnVlLCJmYWNlIjp0cnVlfSwiaWF0IjoxNTUyMDY2MTUzLCJleHAiOjE1NTIxNTI1NTMsImF1ZCI6ImlkY2hlY2siLCJpc3MiOiJIZWxsb3NvZGEiLCJzdWIiOiI1NjcyOWI2Yjc3YzgyMjg4Zjc0NmMwY2YifQ.PQ7CVgoHklg1nutIrQ8QvNq8sbZXnn07Be9ZaCwzlCSEv67no75q0ShlTFP3Gba5X1gwqRYjykLuj7gIPXUGcA",
            'Content-type': 'application/json; charset=utf-8'
        },
        body: JSON.stringify({
            productId: faker.random.uuid(),
        })
    }]
}, console.log);
```

The first is a request to an /auth endpoint to retrieve a bearer token. I want to pass that bearer token into the second request. Right now it is hardcoded.

A side problem i found when using autocannon in this way and `faker.random.uuid()` it does not generate a new uuid for for every request in the duration it reusing the same one.

**Comment by mcollina** [comment]
You will need to use https://github.com/mcollina/autocannon/blob/master/README.md#client-api to modify the request, ad showed in the example above.
