### ISSUE TITLE
Dearest Matteo Collina

### ISSUE THREAD

**Issue by alexhultman-2fa** [mcollina/autocannon#286]
Hello Matteo,

I hope you'll read this and consider what I'm telling you. It is intended for the better.

First off, autocannon is absolutely in no shape or form whatsoever in any universe faster than wrk. This is entirely absurd and technically impossible in every sense of the word.

Benchmarking a fast server with autocannon is benchmarking nothing other than autocannon itself. This has a catastrophically tainting effect and spoils the entire test. Autocannon is running at 100% CPU time and it's leaving the tested server not even remotely stressed whatsoever, at what is essentially 2% CPU time.

This is why autocannon is reporting a result of 23k req/seq and a latency of 12ms - these are the performance results of autocannon itself. Autocannon becomes the limiting factor in this, not the tested server. This is what you fail to accept when you write on your readme that "on my machine is is faster". No it isn't.

If you pick up wrk, numbers are entirely different. With wrk we see that the tested server actually gets stressed at 100% CPU time and the numbers reported are deterministically accurate at 180k req/sec and with a max latency of 600 micro seconds. That's 0.6 milliseconds latency - a whole mountain of difference compared to the ridiculous report of 12 milliseconds! And seriously, 23k req/sec? It's so far from the truth you can possibly come. It's capped, can't you see that it's capped?

Okay so the reason why I make this post is because you are very active in the nodejs core, making changes based on inaccurate benchmarking like these. Recently you and your commit alone dropped performance of nodejs 20% in a PR that you claimed improved performance by 5%. This is because you don't know, or care to admit that you're tweaking things based on inaccurate testing.

You use autocannon to test Fastify, and you think you get better results with autocannon than with wrk, so you make changes to nodejs that harm rather than improve. You tweak for what is essentially measurement error and that's why we get things like nodejs 12.7 where performance of the fastest servers drop 20%.

The reason why you see better results with autocannon (and hence refuse to accept wrk is much more accurate) when measuring Fastify is somewhat low level and complex to understand without operating system expertise, but let me give you a simplified explanation. I've seen this myself before - when adding extra work (more CPU delay) actually can show an improvement in performance tests even though that is logically nonsense as you just added work. That's not how time works.

The simplified explanation is that if the client (autocannon) and server (Fastify) both have roughly the same performance (they do), they will resonate together - sing - if you will. They will appear to perform slightly better than when tested with wrk, which will not sing in the same frequency as autocannon/Fastify. That's why you see sightly lower performance, and your mistake is not recognizing this to be a measurement error but rather go for this small supposed improvement and end up making a bad PR that cuts performance for the top performing servers.

Please, do start measuring with wrk rather than autocannon when you make changes to nodejs. These changes really harm those who are actually pushing nodejs to the performance limits way up there. Everytime you think you improve things with a PR, please think twice before merging things.

Nodejs 12.7 lowered performance by 20% compared to nodejs 12.6 and we did bisect down to your very PR as being the culprit.

This message is meant to be entirely neutral and scientific - you need to do better testing and stop pretending your own scripted, highly indeterministic and stuttery client is better than the industry standard written in deterministically performing C. Again, 180k in wrk at 100% CPU time vs. 23k in autocannon at an entirely idle usage of 2% CPU time is the smoking gun here, you can't argue that this thing is faster.

Alright, hope you can take scientific criticism - that's the whole point of science, you know. When complete nonsense is presented like it is here.

**Comment by alexhultman** [comment]
I've come up with a simple explanation which is technical yet simple to grasp: 

The reason why you **think** autocannon is faster than wrk (even though the above simple tests **clearly** disproves this) has to do with the rescheduling overhead in the kernel when one end finishes much faster than the other end.

When a fast client (wrk) executes its operations much faster than the slow server (Node.js), the client will have to yield to the scheduler. This because, well, it is no longer executing so it is idle and needs to be stopped by the kernel.

Whenever the slow server finishes its execution, the client will have to be rescheduled, woken up from idle, to proceed with the next request. This overhead of scheduling/yielding execution all the time adds up as a small overhead that **makes it look like** wrk is "slower" when measuring slower servers like Node.js.

Compare this to when you measure with autocannon; both the client and the server will execute their parts roughly in the same frequencies and never really end up idle - at least they end up idle with a much smaller probability than before. This **makes it look like** autocannon is slightly faster than wrk, simply because you have less kernel scheduling overhead.

So when you use this small "increase" in performance as an indication that you are making changes that are good, you're really optimizing for measurement error. You're optimizing to a local optima, not the global optima.

That's why I I'm telling this. Please do better measurements when you tinker with Node.js core, as it affect my stake in it negatively when performance suddenly drop from 120k req/sec to 95k in one single point release.

**Comment by mcollina** [comment]
Thank you for your feedback.
