### ISSUE TITLE
Golang vs Node -- WRK & Autocannon

### ISSUE THREAD

**Issue by ynwd** [mcollina/autocannon#300]
# Question:
why are the results different?

# WRK:

Nodejs:
```
e560@linux:~$ wrk -t1 -c100 http://localhost:3000
Running 10s test @ http://localhost:3000
  1 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.42ms  638.17us  12.23ms   71.72%
    Req/Sec    29.45k     3.56k   34.43k    68.00%
  292671 requests in 10.00s, 48.84MB read
Requests/sec:  29254.95
Transfer/sec:      4.88MB
```
Golang
```
e560@linux:~$ wrk -t1 -c100 http://localhost:3000
Running 10s test @ http://localhost:3000
  1 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   846.21us    1.00ms  42.74ms   93.51%
    Req/Sec    91.46k     4.82k   95.95k    94.00%
  909707 requests in 10.02s, 130.13MB read
Requests/sec:  90808.78
Transfer/sec:     12.99MB

```

# Autocannon

```
autocannon -c 100 http://localhost:3000
```

![Screenshot from 2020-11-16 11-03-16](https://user-images.githubusercontent.com/10122431/99213325-e8c06a00-27ff-11eb-810e-ce0aecbfcb03.png)

![Screenshot from 2020-11-16 10-57-58](https://user-images.githubusercontent.com/10122431/99213339-f4ac2c00-27ff-11eb-9dee-3f491ed49da6.png)

**Comment by mcollina** [comment]
Could you please paste the content instead of using screenshots?

It's likely that `autocannon` is capping on the CPU, have you check with `top` or analog if it reaches 100%?

**Comment by qballer** [comment]
While not my issue, I already typed it because I was curious: 

```go 
package main
import (
	"fmt"
	"net/http"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request){
		fmt.Fprintf(w, "Hello Benchmark")
	})

	fmt.Println("listening...")
	http.ListenAndServe("0.0.0.0:3000", nil)
}
```
```js
const http = require('http')
const requestListener = (req, res ) => {
    res.writeHead(200)
    res.end('Hello Benchmark')
}

const server = http.createServer(requestListener)
process.stdout.write('Starting...')
server.listen(3000)
```

**Comment by salmanm** [comment]
I run against both Go and Node servers for 2 seconds and this is what I got:

| Tool | Go (Requests/sec) | Node (Requests/sec) |
| ------------- |:-------------:|:-----:|
| wrk `-t 1` | 92k | 41k |
| wrk `-t 2` | 44k | 21k |
| wrk `-t 4` | 22k | 10k |
| | | |
| autocannon | 57k | 43k |
| autocannon (2 workers `-w 2`) | 96k | 44k |
| autocannon (4 workers `-w 4`) | 112k | 43k |

Indeed, autocannon gets capped on the CPU which resulted in 57k average r/s. But it's evident that it outperforms wrk with 2 workers and even better with 4.

Note that Node js server is also capped at around 43/44k. This is again due to CPU. A cluster would perform way better.

Now, why wrk output goes down as I increase threads, is a mystery to me. 😅
