### ISSUE TITLE
feature_request: make autocannon run indefinitely whilst emitting reports periodically

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [mcollina/autocannon#92]
In a microservice architecture it is nice to have constant load on the systems to track p99 latencies.

This talk gives a nice real world example done by Uber. https://www.youtube.com/watch?v=kb-m2fasdDY

Hence it would be cool to have:

``` js
const instance = autocannon({
  url: 'https://url.url',
  connections: 30, 
  pipelining: 3,
  duration: 0 // for safe infinite
}, console.log)

instance.on('report', sendToAnalytics)
```

**Comment by mcollina** [comment]
I'm missing what the 'report' should do, compared to the callback.

Would you like to send a pr?

**Comment by eljefedelrodeodeljefe** [comment]
The idea would be streaming the report to some kind of UI to have a continuous metrics. Sure, will PR or maybe get @thekemkid into the loop.

**Comment by mcollina** [comment]
There is already an event fired (the one that updates the progress bar in the CLI), isn't that enough?

**Comment by eljefedelrodeodeljefe** [comment]
Sure my point is rather having autocannon running forever reliably by passing a 0 duration or similar. I believe there is nothing for it, right?

**Comment by mcollina** [comment]
At the moment no. Most of the code is written to be extremely low overhead,
and I fear it might cause either a slowdown or a decently sized rewrite.

A quick-and-dirty solution is to reschdule autocannon when it finishes.
However, this would kill the tcp sockets.

Would you be ok with emitting fresh data every 5-10 seconds?

The problem is that autocannon will generate the maximum amount of load in
that interval given the chosen number of connections. You will have to set
the overallRate to limit this.
Il giorno dom 9 ott 2016 alle 22:38 Robert Jefe Lindstädt <
notifications@github.com> ha scritto:
